### ISSUE TITLE
请问在哪里可以修改移动设备端显示的标题栏长度呢？

### ISSUE THREAD

**Issue by luoyangchun** [heymind/OneDrive-Index-Cloudflare-Worker#11]
现在文件标题栏太长了，还要左右滑动才能看见文件大小，不知道在哪里可以修改

![Gif_20200206_184427](https://user-images.githubusercontent.com/31247167/74894977-610e1200-53cb-11ea-830f-1d9d1aa1249b.gif)

**Comment by heymind** [comment]
css 在这里
https://github.com/heymind/OneDrive-Index-Cloudflare-Worker/blob/master/themes/material.css

不如直接加个样式覆盖掉
