### ISSUE TITLE
【建议】添加设置密码功能

### ISSUE THREAD

**Issue by jyeric** [heymind/OneDrive-Index-Cloudflare-Worker#13]
RT，onedrive网盘里面可能会存一些不宜进行分享的内容。如果能设置密码的话就好了。

**Comment by SomeBottle** [comment]
鉴于workers的部分限制，我觉得这个功能不太方便

**Comment by heymind** [comment]
密码也只是保护防止列出某个目录下的文件列表，原理上不能满足阻止下载子目录下文件。

**Comment by ryank231231** [comment]
可以使用 HTTP Basic Auth 来加密。
参考：[https://github.com/maple3142/GDIndex](https://github.com/maple3142/GDIndex)

**Comment by reycn** [comment]
@jyeric 我实现了加密可以看看这里 https://github.com/reycn/OneDrive-Index-Cloudflare-Worker

**Comment by heymind** [comment]
#23
