### ISSUE TITLE
得不到Code

### ISSUE THREAD

**Issue by roaming-debug** [heymind/OneDrive-Index-Cloudflare-Worker#15]
在按照视频中的方法的步骤之后，尝试获取code，直接跳转回原来的网址[graph-api-auth](https://heymind.github.io/tools/microsoft-graph-api-auth)

**Comment by jyeric** [comment]
@driftingdream 将逗号改为空格试试
#2 中有讲到

**Comment by heymind** [comment]
#2

**Comment by zachpay** [comment]
同样获取不到 code 前置的 3个权限都设置好了
 web url 也设置好了 第四步点完 获取不到 code  视频在哪里啊 求链接

**Comment by zachpay** [comment]
> @driftingdream 将逗号改为空格试试
> #2 中有讲到

Sope中 默认是空格分割的哦，https://heymind.github.io/tools/microsoft-graph-api-auth 第四步获取不到 code 有人遇到过吗
