### ISSUE TITLE
Worker无法显示

### ISSUE THREAD

**Issue by LuciferGabriel** [heymind/OneDrive-Index-Cloudflare-Worker#16]
正确填写完参数后出现{"code":"itemNotFound","message":"Item does not exist","innerError":{"request-id":"80847114-1c29-4425-88d3-ee7f71b13f00","date":"2020-03-08T21:14:01"}}

**Comment by SomeBottle** [comment]
配置项base是否合理配置

**Comment by Koogoo** [comment]
500 Internal Server Error
content-length:151
content-type:application/json
{"code":"itemNotFound","message":"Item does not exist","innerError":{"request-id":"b3cd5f71-0fc4-41f5-bdc2-eb1e20b28789","date":"2020-03-16T12:10:00"}}

=========================================
出现同样的问题。。。

**Comment by SomeBottle** [comment]
base项是如何配置的，对应目录是不是空的？

**Comment by Koogoo** [comment]
有按这里的建议改过：https://github.com/heymind/OneDrive-Index-Cloudflare-Worker/issues/2

${pathname == "/" ? "" : pathname}

**Comment by heymind** [comment]
#2
