### ISSUE TITLE
根目录无法使用

### ISSUE THREAD

**Issue by djnwzs** [heymind/OneDrive-Index-Cloudflare-Worker#17]
"message":"Resource not found for the segment 'root:'
还有使用microsoft-graph-api-auth工具的
offline_access,Files.Read,Files.Read.All应将逗号改为空格才会生效

**Comment by djnwzs** [comment]
我fork了一份，小改了下，可以使用根目录了，使用缓存时，超过最大值也不会跳转错误页面了
https://github.com/djnwzs/OneDrive-Index-Cloudflare-Worker

**Comment by heymind** [comment]
#18
