### ISSUE TITLE
文件下载有问题

### ISSUE THREAD

**Issue by Micraow** [heymind/OneDrive-Index-Cloudflare-Worker#19]
有一些超过100MB的文件在下载的时候cloudflare会报错，错误代码****************1101****************
请问这个怎么解决？

**Comment by JiangGua** [comment]
亲测有效：https://github.com/djnwzs/OneDrive-Index-Cloudflare-Worker/commit/aac3525472d0d983ba8f4b4e53914e33b37c00de

**Comment by Micraow** [comment]
？这个需要配置吗？我没有动任何配置，大于一百多兆的文件无法下载cloudflare 显示1101日志显示500

**Comment by heymind** [comment]
https://github.com/heymind/OneDrive-Index-Cloudflare-Worker/commit/6a30f8c4752aac213d5fd050a812d94fe7507eef
