### ISSUE TITLE
Cache 有问题

### ISSUE THREAD

**Issue by Micraow** [heymind/OneDrive-Index-Cloudflare-Worker#20]
只要打开cache ,下载大于100M的文件就会报错。无论缓存标准是多少。

**Comment by heymind** [comment]
可以提供下更多的细节吗？

**Comment by Micraow** [comment]
好的，当cache配置为true(文件大小参数未更改）时，下载较大的文件（100MB）左右，就会显示1101错误（来自cloudflare）,日志中显示500。

**Comment by djnwzs** [comment]
console.info(`No cache ${request.url} because file_size(${fileSize}) > limit(${config.cache.chunkedCacheLimit})`);
这里原版是少了个config，改成这句话就ok了

**Comment by heymind** [comment]
#19
