### ISSUE TITLE
English Translation For README

### ISSUE THREAD

**Issue by alenpaulvarghese** [heymind/OneDrive-Index-Cloudflare-Worker#26]
Please Include the **English** translation for Readme.md Thanks.

**Comment by reycn** [comment]
@alenpaul2001 English translation is temporarily available [here](https://github.com/reycn/OneDrive-Index-Cloudflare-Worker/blob/master/readme.en.md) and I'll propose a PR later.

 Enjoy. 😁

**Comment by alenpaulvarghese** [comment]
> @alenpaul2001 English translation is temporarily available [here](https://github.com/reycn/OneDrive-Index-Cloudflare-Worker/blob/master/readme.en.md) and I'll propose a PR later.
> 
>  Enjoy. 😁

Thanks 😊
