### ISSUE TITLE
加密无法正常使用

### ISSUE THREAD

**Issue by reycn** [heymind/OneDrive-Index-Cloudflare-Worker#28]
由于本人疏忽，粘贴代码时遗漏主逻辑，导致当前版本无法正常使用加密功能。

故开 Issue 提醒各位，已经提交正确版本的 PR [\[Urgent\] 修复访问密码未生效问题](https://github.com/heymind/OneDrive-Index-Cloudflare-Worker/pull/27)。

为避免不必要的消极影响，请 owner 合并最新 PR 或回滚为无加密版本，并之后关闭此 issue。

深表歉意。

**Comment by reycn** [comment]
已经合并，感谢 owner 😀。

再次对各位表示歉意。

**Comment by sayainchina** [comment]
不知道大佬是否能添加一个目录加密的功能，谢谢~
