### ISSUE TITLE
取消基本认证

### ISSUE THREAD

**Issue by thegreatestminer** [heymind/OneDrive-Index-Cloudflare-Worker#29]
我希望我的网站是公开的，不需要任何密码就可以访问.

变数清空后就没有作用了......
```
const NAME = ""
const PASS = ""
```

我对机器翻译表示歉意.

**Comment by reycn** [comment]
@thegreatestminer PR created [here](https://github.com/heymind/OneDrive-Index-Cloudflare-Worker/pull/30). 

Enjoy. 😁

**Comment by sayainchina** [comment]
> @thegreatestminer PR created [here](https://github.com/heymind/OneDrive-Index-Cloudflare-Worker/pull/30).
> 
> Enjoy. 😁

不知道能不能做到下级目录没有密码，上级目录有密码，类似Goindex一样，可以利用.password进行加密呢？

**Comment by thegreatestminer** [comment]
thank you
