### ISSUE TITLE
最后get_token

### ISSUE THREAD

**Issue by bebescom** [heymind/OneDrive-Index-Cloudflare-Worker#3]
"error":"invalid_grant","error_description":"AADSTS9002313: Invalid request. Request is malformed or invalid
个人版和教育版都这样报错

**Comment by bebescom** [comment]
个人版的可以用了，教育版的只在应用程序权限里添加Files.Read.All，才能获取token，但是没有什么用

**Comment by joostshao** [comment]
一样，第四步失败

**Comment by heymind** [comment]
#2
