### ISSUE TITLE
Access Token has Expired

### ISSUE THREAD

**Issue by amanrajOO7** [heymind/OneDrive-Index-Cloudflare-Worker#41]
I've successfully hosted the index on my cloudflare worker. But after sometime I'm getting this error when I'm trying to open the Index - 

"{"code":"InvalidAuthenticationToken","message":"Access token has expired.","innerError":{"date":"2020-06-29T08:49:21","request-id":"597dcfcd-fe73-4e92-9af7-134ca46da70e"}}"

Anyway to fix it?

**Comment by heymind** [comment]
#24
