### ISSUE TITLE
无法返回code

### ISSUE THREAD

**Issue by luoyangchun** [heymind/OneDrive-Index-Cloudflare-Worker#8]
>office365订阅类型：msdn e3
>正常使用rclone，已开放所需api权限
>使用工具 microsoft-graph-api-auth无法返回第五步需要的code

**Comment by fjdjsifnk** [comment]
> > office365订阅类型：msdn e3
> > 正常使用rclone，已开放所需api权限
> > 使用工具 microsoft-graph-api-auth无法返回第五步需要的code

把offline_access,Files.Read,Files.Read.All的,换成空格就可以获取code，然后后面的我这个不行，你可以研究研究，研究出来了别忘了说一声哈

**Comment by luoyangchun** [comment]
> > > office365订阅类型：msdn e3
> > > 正常使用rclone，已开放所需api权限
> > > 使用工具 microsoft-graph-api-auth无法返回第五步需要的code
> 
> 把offline_access,Files.Read,Files.Read.All的,换成空格就可以获取code，然后后面的我这个不行，你可以研究研究，研究出来了别忘了说一声哈

换了个msdn e5试用号，按你说的用空格替换`,`可以获取code了：
![2020-02-06_182110](https://user-images.githubusercontent.com/31247167/73928387-f7433200-490d-11ea-8e76-47171ff4b340.png)
顺利获取`Refresh Token`，正常列出目录。

但之前的e5的号还是不能获取code，一会儿试试重新注册应用。

**Comment by luoyangchun** [comment]
> > > office365订阅类型：msdn e3
> > > 正常使用rclone，已开放所需api权限
> > > 使用工具 microsoft-graph-api-auth无法返回第五步需要的code
> 
> 把offline_access,Files.Read,Files.Read.All的,换成空格就可以获取code，然后后面的我这个不行，你可以研究研究，研究出来了别忘了说一声哈

权限给大一点，应用注册时，将`受支持的帐户类型`改成`任何组织目录...`即可。

![2020-02-06_185251](https://user-images.githubusercontent.com/31247167/73931558-7dae4280-4913-11ea-9e16-72710d525a1a.png)

**Comment by fjdjsifnk** [comment]
> > > > office365订阅类型：msdn e3
> > > > 正常使用rclone，已开放所需api权限
> > > > 使用工具 microsoft-graph-api-auth无法返回第五步需要的code
> > 
> > 
> > 把offline_access,Files.Read,Files.Read.All的,换成空格就可以获取code，然后后面的我这个不行，你可以研究研究，研究出来了别忘了说一声哈
> 
> 权限给大一点，应用注册时，将`受支持的帐户类型`改成`任何组织目录...`即可。
> 
> ![2020-02-06_185251](https://user-images.githubusercontent.com/31247167/73931558-7dae4280-4913-11ea-9e16-72710d525a1a.png)

第五步我一直不行。这个我一直设置的这个
第五步返回这个
![QQ截图20200206202513](https://user-images.githubusercontent.com/59532049/73936962-e6e78300-491e-11ea-8def-2790d09f7880.png)

**Comment by luoyangchun** [comment]
> > > > > office365订阅类型：msdn e3
> > > > > 正常使用rclone，已开放所需api权限
> > > > > 使用工具 microsoft-graph-api-auth无法返回第五步需要的code
> > > 
> > > 
> > > 把offline_access,Files.Read,Files.Read.All的,换成空格就可以获取code，然后后面的我这个不行，你可以研究研究，研究出来了别忘了说一声哈
> > 
> > 
> > 权限给大一点，应用注册时，将`受支持的帐户类型`改成`任何组织目录...`即可。
> > ![2020-02-06_185251](https://user-images.githubusercontent.com/31247167/73931558-7dae4280-4913-11ea-9e16-72710d525a1a.png)
> 
> 第五步我一直不行。这个我一直设置的这个
> 第五步返回这个
> ![QQ截图20200206202513](https://user-images.githubusercontent.com/59532049/73936962-e6e78300-491e-11ea-8def-2790d09f7880.png)

哈。这就结束了呀。Refresh Token就在里面，你Ctrl+F找下就能看到啦

**Comment by fjdjsifnk** [comment]
> > > > > > office365订阅类型：msdn e3
> > > > > > 正常使用rclone，已开放所需api权限
> > > > > > 使用工具 microsoft-graph-api-auth无法返回第五步需要的code
> > > > 
> > > > 
> > > > 把offline_access,Files.Read,Files.Read.All的,换成空格就可以获取code，然后后面的我这个不行，你可以研究研究，研究出来了别忘了说一声哈
> > > 
> > > 
> > > 权限给大一点，应用注册时，将`受支持的帐户类型`改成`任何组织目录...`即可。
> > > ![2020-02-06_185251](https://user-images.githubusercontent.com/31247167/73931558-7dae4280-4913-11ea-9e16-72710d525a1a.png)
> > 
> > 
> > 第五步我一直不行。这个我一直设置的这个
> > 第五步返回这个
> > ![QQ截图20200206202513](https://user-images.githubusercontent.com/59532049/73936962-e6e78300-491e-11ea-8def-2790d09f7880.png)
> 
> 哈。这就结束了呀。Refresh Token就在里面，你Ctrl+F找下就能看到啦

谢了大佬，我一直在这琢磨，一直没想起来还能这样
